# Generated by Django 5.2.6 on 2025-09-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('TEXTBOOK', 'Textbook'), ('ELECTRONICS', 'Electronics'), ('FURNITURE', 'Furniture'), ('CLOTHING', 'Clothing'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'Like New'), ('GOOD', 'Gently Used'), ('FAIR', 'Fair')], default='GOOD', max_length=20)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_images/')),
            ],
        ),
    ]
